# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cf2946d9c3b6e85ba5ea9bfc92832b7906f3326c58d5912b751c677226ac620bdb9d6fd8c55ed7d3849926de216e4d37daa21b48b644e2b6d38d849d732e516

test:
  secret_key_base: e24ee15dcf3421b8566afc40574e59d831ca8d5dbfcd828d959e40fc94c9648157a9c206a375886b9fe71d5cdfeedf3502d1aec0d488db416a095dce3195edcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
